name: Build, Analyze, and Scans

on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: [self-hosted]
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Scout CLI
        run: |
          curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Docker Scout file scan
        run: |
          docker scout quickview . --output sarif > scout-results.sarif

      - name: Upload Scout scan results
        uses: actions/upload-artifact@v4
        with:
          name: scout-file-scan-results
          path: scout-results.sarif

      
