name: Build, Analyze, and Scan

on:
  push:
    branches:
      - main
jobs:
  build-analyze-scan:
    name: Build, Analyze, and Scan
    runs-on: [self-hosted]
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependecies
        run: npm install

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Scout Scan (Dockerfile in repo)
        uses: docker/scout-action@v1
        with:
          command: quickview
          context: .
          sarif-file: scout-results.sarif
          exit-code: 0 

      
